name: Work_flow file
on: 
   workflow_dispatch:
jobs:
 first_job:
    name: This is the first job
    runs-on: ubuntu-latest
    steps:
      - name: Signle line run step
        run: echo testing in step1
      - name: Multi line run step
        run: |
              echo testing step2
              echo testing step2 line2
      
 
