name: This is first GHA file
on: 
   workflow_dispatch:
jobs:
 first_job:
    name: this is the first job
    runs-on: ubuntu-latest
    steps:
      - name: this is the first step
        run: echo hello world
      - name: multi line step
        run: |
              echo testing line2
              echo testing line3
      
 
