name: Vars_secrets
on:
  workflow_dispatch:
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: var prints
        run: echo ${{vars.my_repo_var1}}
  secrets:
    runs-on: ubuntu-latest
    needs: vars
    steps:
      - name: secrets prints
        run: echo ${{secrets.my_repo_secr1}}
